/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yhsh_createsolib_MyJniNative */

#ifndef _Included_cn_yhsh_createsolib_MyJniNative
#define _Included_cn_yhsh_createsolib_MyJniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yhsh_createsolib_MyJniNative
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yhsh_createsolib_MyJniNative_helloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
